fos_oauth_server:
    db_driver:           orm
    client_class:        App\CoreBundle\Entity\Client
    access_token_class:  App\CoreBundle\Entity\AccessToken
    refresh_token_class: App\CoreBundle\Entity\RefreshToken
    auth_code_class:     App\CoreBundle\Entity\AuthCode
    service:
        user_provider: fos_user.user_provider.username            # This property will be used when valid credentials are given to load the user upon access token creation
