# fos_user_security:
#     resource: "@FOSUserBundle/Resources/config/routing/security.xml"
# fos_user_profile:
#     resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
#     prefix: /profile
# fos_user_register:
#     resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
#     prefix: /register
# fos_user_resetting:
#     resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
#     prefix: /resetting
# fos_user_change_password:
#     resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
#     prefix: /profile

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /api/doc

# FOSAuthServerBundle
fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"

app_corebundle_rest_controller:
    type: rest
    resource: App\CoreBundle\Controller\CoreController

# app_rest:
#     path: /rest/{id}
#     defaults: { _controller: 'App\CoreBundle\Controller\CoreController::restAction' }

nelmio-api-doc:
    resource: "@NelmioApiDocBundle/Resources/config/routing/swaggerui.xml"
    prefix:   /documentation